/*
	User-mode header file names end in "u" and kernel-mode header file names end in "k"

	Here filtering is performed at sublayer level
*/

#include "wdf_main.h"
#include "ioctl.h"
#include "wfp.h"
#include "wfp_driver_src.h"

UNICODE_STRING DEVICE_NAME = RTL_CONSTANT_STRING(DEVICE_STRING);
WDFDEVICE g_Device = NULL;

/*
	Returns WDF device object reference.
	Example usage: Classifyout function in wfp.c
*/
WDFDEVICE* GGetWDFDevice()
{
	return &g_Device;
}

DriverUnload
(
	_In_ WDFDRIVER driver
)
{
	KdPrint(("MyNetworkFilter: DriverUnload -> Unloading Driver... \n"));
	//TODO: perform unregister operations when the driver unloads

	UnInitializeWfp();
	UNREFERENCED_PARAMETER(driver);

	KdPrint(("MyNetworkFilter: DriverUnload -> Driver unloaded. Bye-:) \n"));
}

/*
	Initialize driver and device
*/
NTSTATUS
InitDriverObjects(
	PDRIVER_OBJECT pDriverObject,
	PUNICODE_STRING pRegistryPath,
	WDFDRIVER* driver,
	WDFDEVICE* device 
)
{
	NTSTATUS status;
	WDF_DRIVER_CONFIG config;
	PWDFDEVICE_INIT pDeviceInit = NULL;

	WDF_DRIVER_CONFIG_INIT(&config, WDF_NO_EVENT_CALLBACK);

	//unregister everything when the driver unloads using EvtDriverUnload callback
	config.DriverInitFlags |= WdfDriverInitNonPnpDriver;
	config.EvtDriverUnload = DriverUnload;

	KdPrint(("MyNetworkFilter: DriverEntry -> InitDriverObjects -> Creating Driver... \n"));
	status = WdfDriverCreate(
				pDriverObject,
				pRegistryPath,
				WDF_NO_OBJECT_ATTRIBUTES,
				&config,
				driver
			);

	if (!NT_SUCCESS(status)) {
		goto Exit;
	}

	KdPrint(("MyNetworkFilter: DriverEntry -> InitDriverObjects -> Successfully created driver. \n"));
	KdPrint(("MyNetworkFilter: DriverEntry -> InitDriverObjects -> Allocating Device... \n"));

	/*
		Allocating resource(device) to driver
		SDDL_DEVOBJ_KERNEL_ONLY is the "empty" ACL. 
		User-mode code (including processes running as system) cannot open the device.
	*/
	pDeviceInit = WdfControlDeviceInitAllocate(*driver, &SDDL_DEVOBJ_SYS_ALL_ADM_ALL);

	if (!pDeviceInit) {
		status = STATUS_INSUFFICIENT_RESOURCES;
		goto Exit;
	}

	KdPrint(("MyNetworkFilter: DriverEntry -> InitDriverObjects -> Successfully Allocated Device. \n"));

	KdPrint(("MyNetworkFilter: DriverEntry -> InitDriverObjects -> Creating Device... \n"));
	//WdfDeviceInitSetCharacteristics(pDeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);
	WdfDeviceInitSetDeviceType(pDeviceInit, FILE_DEVICE_NETWORK);
	WdfDeviceInitSetCharacteristics(pDeviceInit, FILE_DEVICE_SECURE_OPEN, TRUE);
	status = WdfDeviceInitAssignName(pDeviceInit, &DEVICE_NAME);
	if (!NT_SUCCESS(status))
	{
		KdPrint(("failed to create WDF device name"));
		WdfDeviceInitFree(pDeviceInit);
		goto Exit;
	}

	//IOCTL: initialize file config
	//FileConfigInit(pDeviceInit);
	//KdPrint(("Initialized file config.\n"));

	//Set device context type for IOCTL
	WDF_OBJECT_ATTRIBUTES objAttributes;
	WDF_OBJECT_ATTRIBUTES_INIT(&objAttributes);
	WDF_OBJECT_ATTRIBUTES_SET_CONTEXT_TYPE(&objAttributes,
										   WFP_DEVICE_CONTEXT);

	status = WdfDeviceCreate(&pDeviceInit,
							 &objAttributes,
							 device);

	if (!NT_SUCCESS(status)) {
		KdPrint(("Failed to create device.\n"));
		WdfDeviceInitFree(pDeviceInit);
		goto Exit;
	}

	KdPrint(("Device created.\n"));

	//IOCTL: initialize IO queue
	status = InitializeQueue(*device);

	if (!NT_SUCCESS(status)) {
		goto Exit;
	}

	KdPrint(("MyNetworkFilter: WDF IO Queue initialized."));

	WdfControlFinishInitializing(*device);
	KdPrint(("MyNetworkFilter: Successfully created device. \n"));

Exit:

	if (!NT_SUCCESS(status))	{
		KdPrint(("MyNetworkFilter: Status code: 0x%x \n", status));
		KdPrint(("MyNetworkFilter: DriverEntry -> InitDriverObjects -> Exiting. \n"));
	}
	return status;
}

/*
	PDRIVER_OBJECT => DRIVER_OBJECT*
*/
NTSTATUS
DriverEntry(
	_In_ PDRIVER_OBJECT pDriverObject,
	_In_ PUNICODE_STRING pRegistryPath
)
{
	KdPrint(("MyNetworkFilter: DriverEntry -> Initialing... \n"));

	NTSTATUS status;
	WDFDRIVER driver = NULL;
	PDEVICE_OBJECT pWdmDevice = NULL;

	UNREFERENCED_PARAMETER(g_Device);
	UNREFERENCED_PARAMETER(driver);
	UNREFERENCED_PARAMETER(pWdmDevice);

	KdPrint(("MyNetworkFilter: DriverEntry -> Initializing driver & device.... \n"));

	status = InitDriverObjects(
				pDriverObject,
				pRegistryPath,
				&driver,
				&g_Device
			);

	if (!NT_SUCCESS(status))
	{
		goto Exit;
	}

	KdPrint(("MyNetworkFilter: DriverEntry -> Initializing driver & device successful. \n"));

	//get wdm device instance from wdf instance type
	pWdmDevice = WdfDeviceWdmGetDeviceObject(g_Device);
	status = InitializeWfp(pWdmDevice);

	if (!NT_SUCCESS(status)) {
		//TODO: delete device object
		goto Exit;
	}

	KdPrint(("MyNetworkFilter: DriverEntry -> Wfp initialization successful. \n"));

Exit:

	if (!NT_SUCCESS(status)) {
		KdPrint(("MyNetworkFilter: DriverEntry -> Exiting."));
	}
	return status;
}